#!/usr/bin/env python
"""Publish a trained LoRA adapter to the Hugging Face Hub.

    python scripts/publish_adapter.py \
        --adapter runs/adapters/stage-b \
        --repo <user>/qwen3-vl-satquery \
        --results runs/results.csv

Two shapes, chosen with ``--merge``.

*Adapter only* (default): tens of megabytes. Whoever loads it pulls the pinned
base themselves, so the two cannot drift apart -- the adapter names the exact
base revision it was trained against.

*Merged model* (``--merge``): the adapter folded into the base and saved as one
set of weights, several gigabytes. Loads with a plain ``from_pretrained`` and
serves without peft, which is the simpler story for a submission or a demo. The
cost is that the base revision is now baked in and invisible, so the card
records it explicitly.

The model card is generated from what was actually recorded -- the training
metadata written beside the adapter and the measured benchmark rows -- rather
than typed by hand. A card is the only thing most readers will see, and one
whose numbers were retyped is one nobody can check.

By default the script **refuses to publish an adapter with no measured delta**.
An adapter with no before-and-after is exactly the unverifiable claim this
project exists not to make. ``--allow-unmeasured`` overrides it for an interim
checkpoint, and says so on the card.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

CARD = """---
base_model: {base_model}
base_model_relation: {relation}
library_name: {library}
license: apache-2.0
language:
  - en
tags:
  - remote-sensing
  - earth-observation
  - vision-language
  - lora
  - sar
  - sentinel
datasets:
  - BIFOLD-BigEarthNetv2-0/BigEarthNet.txt
pipeline_tag: image-text-to-text
---

# {repo}

{headline} for multimodal remote-sensing analysis:
optical and SAR imagery, land cover, bi-temporal change, and cross-modal
reasoning over co-registered Sentinel-1 and Sentinel-2 pairs.

Built for **Smart India Hackathon 2026, ISRO problem statement SIH26167**.

{delta_section}

## What is adapted

Three surfaces, not one. A LoRA confined to a language model's attention blocks
leaves the visual domain shift unlearned, and remote-sensing imagery is exactly
where that shift lives.

| surface | what it decides |
| --- | --- |
| language stack | how the answer is worded |
| vision-language projector | how visual features reach the language model |
| vision encoder | how those features are formed in the first place |

Target modules are discovered by walking the loaded model rather than hardcoded,
because a name that matches nothing produces no adapter and no error.

```
{targets}
```

## Training

| | |
| --- | --- |
| Base model | `{base_model}` |
| Base revision | `{base_revision}` |
| LoRA rank / alpha | {rank} / {alpha} |
| Learning rate | {lr} ({scheduler}, {warmup:.0%} warmup) |
| Precision | {precision} |
| Effective batch | {effective_batch} |
| Epochs | {epochs} |
| Seed | {seed} |
| Records | {records:,} |
| Evidence preamble | {evidence_rate:.0%} of records |

Toolchain: {toolchain}

### The evidence preamble

At inference this model is handed measurements computed from the pixels by
deterministic tools before its task prompt:

```
Measurements from image-analysis tools that have already run on these
images. Treat them as reliable and do not contradict them:
- water fraction from optical NDWI: 0.3151
- land cover classes present: arable land, pastures

<task prompt>
```

Roughly {evidence_rate:.0%} of training records carry one, generated by the same
function the serving path calls. A model adapted only on bare prompts has never
seen this and either ignores the measurements or argues with them. Preambles are
never contradictory: where a measurement could not be shown to agree with the
gold answer, the record was emitted without one.

## Data

`BIFOLD-BigEarthNetv2-0/BigEarthNet.txt` (CDLA-Permissive-1.0), cleaned before
sampling:

- Rows asking for **country, season or climate zone** are dropped. Nothing in a
  picture of farmland says *Austria*, and training on those produces confident
  geographic hallucination on unseen regions.
- Captions carry the same contamination inline, so the acquisition clause and
  climate-zone phrase are redacted and the land-cover description kept. A caption
  still naming its country after redaction is dropped rather than patched.
- Patches flagged `contains_cloud_or_shadow` or `contains_seasonal_snow` are
  removed; a cloudy patch teaches nothing about land cover.

## Limitations

Read these before trusting a number from it.

- **Europe only.** BigEarthNet contains no Indian scene. This model has not seen
  the terrain of the evaluation domain it was built for.
- **10 m, 120x120 patches.** Sub-metre imagery is a different visual regime.
- **CORINE is a European taxonomy.** Land-cover vocabulary transfers poorly to
  regions its classes were not designed for.
- **Single-date for land cover.** Bi-temporal capability comes from the task
  mixture, not from BigEarthNet.
- The adapter is not a substitute for the deterministic measurement tools it was
  trained to defer to. It is most useful inside a system that measures first.

## Use

{usage}

---

Generated from recorded run metadata on {timestamp}.
"""


def merge_adapter(adapter: Path, meta: dict[str, Any], out: Path) -> Path:
    """Fold the adapter into the base and write one set of weights.

    Needs the full base in memory -- several gigabytes -- so this runs on the
    training host rather than a laptop. bfloat16 throughout: merging in float32
    and saving would double the upload for no gain, and the model is served in
    bfloat16 anyway.

    The processor is saved alongside. A merged model that cannot tokenise its
    own prompts is a repository people cannot use without going back to the base
    to find out which processor it wanted.
    """
    import torch
    from peft import PeftModel
    from transformers import AutoProcessor, Qwen3VLForConditionalGeneration

    base_model = meta["base_model"]
    revision = meta["base_revision"]
    print(f"loading {base_model} @ {revision[:8]} for merge ...")
    base = Qwen3VLForConditionalGeneration.from_pretrained(
        base_model, revision=revision, dtype=torch.bfloat16, device_map="cpu"
    )
    merged = PeftModel.from_pretrained(base, str(adapter)).merge_and_unload()

    out.mkdir(parents=True, exist_ok=True)
    merged.save_pretrained(str(out), safe_serialization=True)
    AutoProcessor.from_pretrained(base_model, revision=revision).save_pretrained(
        str(out)
    )

    size = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    print(f"merged into {out} ({size / 1e9:.1f} GB)")
    return out


def load_metadata(adapter: Path) -> dict[str, Any]:
    path = adapter / "satquery_training.json"
    if not path.is_file():
        raise SystemExit(
            f"no training metadata at {path}. It is written by "
            f"scripts/train_lora.py; publishing without it would mean a card "
            f"whose configuration nobody can check."
        )
    return json.loads(path.read_text(encoding="utf-8"))


def delta_section(
    results: Path | None, baseline: str, adapted: str
) -> tuple[str, bool]:
    """Render the base-versus-adapted table, and whether one was found."""
    if results is None or not results.is_file():
        return "", False

    from satquery.eval.aggregate import cells_from_results, delta_table, score_matrix
    from satquery.eval.report import read_results

    rows = read_results(results)
    cells = [c for c in cells_from_results(rows) if c["model"] in {baseline, adapted}]
    if not cells or len({c["model"] for c in cells}) < 2:
        return "", False

    cells.sort(key=lambda c: c["model"] != baseline)
    scores = score_matrix(cells)
    provenance = sorted(
        {
            (c.get("prompt_version", "?"), c.get("git_sha", "?"), c["num_samples"])
            for c in cells
        }
    )
    lines = [
        "## Measured effect",
        "",
        "Base and adapted scored by the same harness on the same splits with the",
        "same seed, differing only by the adapter. Scores are normalised against",
        "each metric's own range before aggregation, because CIDEr-D runs to 10",
        "and the rest to 1 -- a raw mean would be captioning alone.",
        "",
        delta_table(scores),
        "",
    ]
    for prompt_version, sha, samples in provenance:
        lines.append(
            f"- prompt version `{prompt_version}`, commit `{sha}`, n={samples}"
        )
    return "\n".join(lines), True


ADAPTER_USAGE = r"""```python
from peft import PeftModel
from transformers import AutoProcessor, Qwen3VLForConditionalGeneration

base = Qwen3VLForConditionalGeneration.from_pretrained(
    "{base_model}", revision="{base_revision}", dtype="bfloat16", device_map="auto"
)
model = PeftModel.from_pretrained(base, "{repo}")
processor = AutoProcessor.from_pretrained("{base_model}", revision="{base_revision}")
```

Served with vLLM, base and adapted are two names on one process, which is what
makes the comparison above hold everything but the adapter fixed:

```bash
python -m vllm.entrypoints.openai.api_server \
  --model {base_model} --revision {base_revision} \
  --enable-lora --lora-modules satquery={repo}
```"""

MERGED_USAGE = r"""The adapter is already folded in, so no peft is needed:

```python
from transformers import AutoProcessor, Qwen3VLForConditionalGeneration

model = Qwen3VLForConditionalGeneration.from_pretrained(
    "{repo}", dtype="bfloat16", device_map="auto"
)
processor = AutoProcessor.from_pretrained("{repo}")
```

```bash
python -m vllm.entrypoints.openai.api_server --model {repo} \
  --served-model-name qwen3-vl-satquery
```

Merged from `{base_model}` at revision `{base_revision}`. That revision is baked
into these weights and cannot be recovered from them, which is why it is
recorded here."""


def build_card(
    meta: dict[str, Any], repo: str, delta: str, measured: bool, merged: bool = False
) -> str:
    lora = meta.get("lora", {})
    if not measured:
        delta = (
            "## Measured effect\n\n"
            "> **No benchmark comparison is recorded for this adapter.** It was\n"
            "> published as an interim checkpoint. Without a base-versus-adapted\n"
            "> table on identical splits there is no evidence the adaptation\n"
            "> helped, and none should be inferred.\n"
        )
    toolchain = ", ".join(f"`{k}=={v}`" for k, v in meta.get("toolchain", {}).items())
    base_model = meta.get("base_model", "Qwen/Qwen3-VL-2B-Instruct")
    base_revision = meta.get("base_revision", "")
    usage_template = MERGED_USAGE if merged else ADAPTER_USAGE
    return CARD.format(
        repo=repo,
        base_model=base_model,
        base_revision=base_revision,
        relation="finetune" if merged else "adapter",
        library="transformers" if merged else "peft",
        headline=(
            f"Full fine-tuned model, merged from `{base_model}`"
            if merged
            else f"LoRA adapter for `{base_model}`"
        ),
        usage=usage_template.format(
            repo=repo, base_model=base_model, base_revision=base_revision
        ),
        delta_section=delta,
        targets="\n".join(meta.get("target_modules", [])) or "(not recorded)",
        rank=lora.get("rank", "?"),
        alpha=lora.get("alpha", "?"),
        lr=lora.get("learning_rate", "?"),
        scheduler=lora.get("scheduler", "cosine"),
        warmup=float(lora.get("warmup_ratio", 0.03)),
        precision=lora.get("precision", "bfloat16"),
        effective_batch=meta.get("effective_batch", "?"),
        epochs=lora.get("epochs", "?"),
        seed=lora.get("seed", "?"),
        records=int(meta.get("records", 0)),
        evidence_rate=float(meta.get("evidence_rate", 0.0)),
        toolchain=toolchain or "(not recorded)",
        timestamp=datetime.now(UTC).strftime("%Y-%m-%d"),
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--adapter", required=True, type=Path, help="peft output directory")
    ap.add_argument(
        "--repo", required=True, help="Hub repo id, e.g. user/qwen3-vl-satquery"
    )
    ap.add_argument("--results", type=Path, default=Path("runs/results.csv"))
    ap.add_argument("--baseline-model", default="qwen3-vl-base")
    ap.add_argument("--adapted-model", default="qwen3-vl-satquery")
    ap.add_argument(
        "--merge",
        action="store_true",
        help="fold the adapter into the base and publish one set of weights",
    )
    ap.add_argument(
        "--public",
        action="store_true",
        help="publish publicly. The default is private: an unfinished model "
        "with provisional numbers is easier to make public later than to unsee.",
    )
    ap.add_argument(
        "--merge-dir",
        type=Path,
        default=None,
        help="where to write merged weights (default: <adapter>/../merged)",
    )
    ap.add_argument(
        "--allow-unmeasured",
        action="store_true",
        help="publish without a base-vs-adapted comparison; the card says so",
    )
    ap.add_argument(
        "--dry-run", action="store_true", help="write the card, push nothing"
    )
    args = ap.parse_args()

    if not (args.adapter / "adapter_config.json").is_file():
        raise SystemExit(
            f"{args.adapter} does not look like a peft adapter "
            f"(no adapter_config.json)."
        )

    meta = load_metadata(args.adapter)
    delta, measured = delta_section(
        args.results, args.baseline_model, args.adapted_model
    )

    if not measured and not args.allow_unmeasured:
        raise SystemExit(
            "no base-versus-adapted comparison found in "
            f"{args.results}. Publishing an adapter with no measured delta is "
            "the unverifiable claim this project exists not to make. Run the "
            "baseline and the adapted sweep, or pass --allow-unmeasured to "
            "publish an interim checkpoint that says so on its card."
        )

    upload_from = args.adapter
    if args.merge:
        upload_from = args.merge_dir or (args.adapter.parent / "merged")
        if args.dry_run:
            print(f"dry run: would merge into {upload_from}")
            upload_from.mkdir(parents=True, exist_ok=True)
        else:
            merge_adapter(args.adapter, meta, upload_from)

    card = build_card(meta, args.repo, delta, measured, merged=args.merge)
    (upload_from / "README.md").write_text(card, encoding="utf-8")
    print(f"wrote {upload_from / 'README.md'} ({len(card):,} chars)")

    if args.dry_run:
        print("\ndry run: nothing pushed")
        return 0

    from huggingface_hub import HfApi

    api = HfApi()
    try:
        who = api.whoami()["name"]
    except Exception as exc:
        raise SystemExit(
            f"not authenticated with the Hub ({type(exc).__name__}). Run "
            f"'huggingface-cli login' or set HF_TOKEN."
        ) from exc
    print(f"authenticated as {who}")

    private = not args.public
    api.create_repo(args.repo, repo_type="model", private=private, exist_ok=True)
    print(f"repo {'private' if private else 'PUBLIC'}")
    # Only the adapter and its card. The base weights are already on the Hub and
    # a checkpoint directory can carry optimiser state that nobody needs.
    api.upload_folder(
        repo_id=args.repo,
        folder_path=str(upload_from),
        ignore_patterns=["checkpoint-*", "optimizer.pt", "*.log", "runs/**"],
    )
    print(f"\npublished https://huggingface.co/{args.repo}")
    if not measured:
        print("  card states that no measured delta is recorded")
    return 0


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
    raise SystemExit(main())
